# Generated by Django 2.0.1 on 2018-01-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['-match_date'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('NIM', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('goals', models.IntegerField()),
                ('shoot', models.IntegerField()),
                ('pass_succees', models.IntegerField()),
                ('pass_unsuccess', models.IntegerField()),
            ],
            options={
                'ordering': ['NIM'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('points', models.IntegerField()),
            ],
            options={
                'ordering': ['-points'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ManyToManyField(related_name='away_team', to='stats.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ManyToManyField(related_name='home_team', to='stats.Team'),
        ),
    ]
