# Generated by Django 2.0.1 on 2018-01-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_auto_20180122_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='goal',
        ),
        migrations.AddField(
            model_name='player',
            name='fouls_committed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='fouls_suffered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='free_kick',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='penalty_kick',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='red_card',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='yellow_card',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='goal_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='goal_for',
            field=models.IntegerField(default=0),
        ),
    ]
