# Generated by Django 2.0.1 on 2018-01-22 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_match_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='ball_possession',
        ),
    ]
