# Generated by Django 2.0.1 on 2018-01-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_remove_player_ball_possession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='ball_possession_away',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='match',
            name='ball_possession_home',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
