# Generated by Django 2.0.1 on 2018-01-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_auto_20180123_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='ball_possession_away',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='match',
            name='ball_possession_home',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='match',
            name='shot_percentage_away',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='match',
            name='shot_percentage_home',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
