# Generated by Django 2.0.1 on 2018-01-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_auto_20180123_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='shot_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
