# Generated by Django 2.0.1 on 2018-01-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0016_auto_20180124_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='ball_recovery_away',
        ),
        migrations.RemoveField(
            model_name='match',
            name='ball_recovery_home',
        ),
        migrations.RemoveField(
            model_name='match',
            name='block_away',
        ),
        migrations.RemoveField(
            model_name='match',
            name='block_home',
        ),
        migrations.RemoveField(
            model_name='match',
            name='clearance_away',
        ),
        migrations.RemoveField(
            model_name='match',
            name='clearance_home',
        ),
        migrations.RemoveField(
            model_name='match',
            name='free_kick_away',
        ),
        migrations.RemoveField(
            model_name='match',
            name='free_kick_home',
        ),
        migrations.RemoveField(
            model_name='match',
            name='penalty_kick_away',
        ),
        migrations.RemoveField(
            model_name='match',
            name='penalty_kick_home',
        ),
        migrations.RemoveField(
            model_name='match',
            name='second_ball_away',
        ),
        migrations.RemoveField(
            model_name='match',
            name='second_ball_home',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ball_recovery',
        ),
        migrations.RemoveField(
            model_name='player',
            name='block',
        ),
        migrations.RemoveField(
            model_name='player',
            name='clearance',
        ),
        migrations.RemoveField(
            model_name='player',
            name='free_kick',
        ),
        migrations.RemoveField(
            model_name='player',
            name='penalty_kick',
        ),
        migrations.RemoveField(
            model_name='player',
            name='second_ball',
        ),
    ]
