# Generated by Django 2.0.1 on 2018-01-25 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0018_auto_20180125_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-win', '-draw', '-lose', '-goal_for', '-goal_against']},
        ),
    ]
