# Generated by Django 2.0.1 on 2018-01-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0019_auto_20180125_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ktm_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/player/ktm'),
        ),
        migrations.AddField(
            model_name='player',
            name='player_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/player/photo'),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/team/'),
        ),
    ]
