# Generated by Django 2.0.1 on 2018-03-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0023_auto_20180201_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_number',
            field=models.IntegerField(default=0),
        ),
    ]
